[package]
name = "cosmic-files"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["unstable-locales"] }
dirs = "5.0.1"
env_logger = "0.10"
lazy_static = "1"
lexical-sort = "0.3.1"
log = "0.4"
paste = "1.0"
serde = { version = "1", features = ["serde_derive"] }
tokio = { version = "1" }
trash = "3.2.0"
# Remote filesystems
remotefs = "0.2"
remotefs-smb = { version = "0.2", optional = true } # uses libsmbclient
remotefs-ssh = { version = "0.2", optional = true } # uses libssh
url = "2.5"
whoami = "1.4"
# Internationalization
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6"
rust-embed = "6"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]
#path = "../libcosmic"

#TODO: clean up and send changes upstream
[dependencies.systemicons]
git = "https://github.com/jackpot51/systemicons"

[features]
default = ["remotefs-ssh", "remotefs-smb", "wgpu"]
wgpu = ["libcosmic/wgpu"]

[patch.crates-io]
smithay-client-toolkit = { git = "https://github.com/pop-os/client-toolkit", branch = "wayland-resize" }

[profile.release-with-debug]
inherits = "release"
debug = true

[target.'cfg(unix)'.dependencies]
fork = "0.1"
